income = input("Tell me your income, I'll tell you your budget:")
print('Your income is $' + income)
i = int(income)
bills = round(i*.5)
spending = round(i*.3)
saving = round(i*.2)
print('Your Budget is...')
print("Savings: $" + str(saving))
print("Bills: $" + str(bills))
print("Spending: $" + str(spending))
